language: go
go:
  - 1.12.x
git:
  depth: 1
install: true
before_script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -t ./...
script:
  - golangci-lint run
notifications:
  email: false
script: bash ./x/coverage.sh
after_success: bash ./x/upload_coverage.sh bash <(curl -s https://codecov.io/bash)
